// Builds a single-file Luau program that runs a plugin's entry point under
// the stubbed Studio environment (scripts/studio_harness.lua).
//
// Why one file: standalone Luau isolates globals per `require`d module, so a
// plugin tree loaded via require could never see the stubbed `plugin`/`game`
// globals. Instead everything is embedded in one chunk and modules are loaded
// with loadstring (which shares the global environment).
import { readFileSync } from "node:fs";

// Embed arbitrary text in a Lua double-quoted string. (Long strings [[...]]
// are NOT usable: the standalone Luau CLI build only supports level-1 long
// brackets, and plugin sources contain "]]".)
function luaString(src) {
  let out = '"';
  for (const ch of String(src)) {
    const code = ch.codePointAt(0);
    if (ch === "\\") out += "\\\\";
    else if (ch === '"') out += '\\"';
    else if (ch === "\n") out += "\\n";
    else if (ch === "\r") out += "\\r";
    else if (code < 0x20) out += "\\" + String(code).padStart(3, "0"); // Luau decimal escape, fixed 3 digits
    else out += ch;
  }
  return out + '"';
}

function luaStr(s) {
  return '"' + String(s).replace(/\\/g, "\\\\").replace(/"/g, '\\"').replace(/\n/g, "\\n") + '"';
}

function luaObj(v) {
  if (Array.isArray(v)) return v.length === 0 ? "{}" : "{" + v.map((x) => luaObj(x)).join(", ") + "}";
  if (v && typeof v === "object") {
    const keys = Object.keys(v);
    if (keys.length === 0) return "{}";
    const parts = keys.map((k) => {
      const key = /^[A-Za-z_][A-Za-z0-9_]*$/.test(k) ? k : `[${luaStr(k)}]`;
      return `${key} = ${luaObj(v[k])}`;
    });
    return "{\n\t" + parts.join(",\n\t") + "\n}";
  }
  if (typeof v === "number") return String(v);
  if (typeof v === "boolean") return v ? "true" : "false";
  return luaStr(v);
}

// cfg:
//   harnessPath  — path to scripts/studio_harness.lua
//   sources      — { [id]: luaSource }
//   graphSpec    — nested { Name, id, children: [...] }
//   dockIds      — dock gui ids that must exist after start()
//   needles      — substrings that must appear in captured print() output
//   label
export function makeSmokeLua(cfg) {
  const harnessSrc = readFileSync(cfg.harnessPath, "utf8");
  const sourcesLua = Object.entries(cfg.sources)
    .map(([id, src]) => `\t${id} = ${luaString(src)},`)
    .join("\n");
  const stringFallbackMap = Object.entries(cfg.stringFallback || {})
    .map(([str, id]) => `\t\t[${luaStr(str)}] = ${luaStr(id)},`)
    .join("\n");

  return `-- generated by scripts/smoke_core.mjs — do not edit
local function fail(msg)
\tprint("SMOKE FAIL: " .. tostring(msg))
\terror("SMOKE FAIL: " .. tostring(msg), 0)
end

local okH, harness = pcall(loadstring(${luaString(harnessSrc)}, "studio_harness"))
if not okH then
\tfail("harness: " .. tostring(harness))
end

local sources = {
${sourcesLua}
}

local env = harness.install()
local graph = harness.buildGraph(${luaObj(cfg.graphSpec)})

local loadedMods = {}
local function loadModule(node)
\tlocal id = rawget(node, "id")
\tif loadedMods[id] ~= nil then
\t\treturn loadedMods[id]
\tend
\tlocal src = sources[id]
\tif src == nil then
\t\tfail("no source for module id: " .. tostring(id))
\tend
\tlocal fn, cerr = loadstring(src, "@" .. id)
\tif not fn then
\t\tfail("compile " .. tostring(id) .. ": " .. tostring(cerr))
\tend
\tlocal mod = fn()
\tloadedMods[id] = mod
\treturn mod
end

local function stringFallbackFn(str)
\tlocal map = {
${stringFallbackMap}
\t}
\tlocal id = map[str]
\tif id ~= nil then
\t\tlocal fn, cerr = loadstring(sources[id], "@" .. id)
\t\tif not fn then
\t\t\tfail("compile " .. tostring(id) .. ": " .. tostring(cerr))
\t\tend
\t\tlocal mod = fn()
\t\tloadedMods[id] = mod
\t\treturn mod
\tend
\treturn nil
end

-- assigned from the MAIN chunk (required: standalone Luau only lets the
-- main chunk rebind the require builtin)
require = harness.makeRequireHook(loadModule, stringFallbackFn)

script = graph
local ok, err = pcall(require, graph)
if not ok then
\tfail("entry: " .. tostring(err))
end

for _, w in ipairs(env.warns) do
\tif w:find("failed to start", 1, true) then
\t\tfail(w)
\tend
end

local docks = {
${cfg.dockIds.map((d) => `\t${luaStr(d)},`).join("\n")}
}
for _, d in ipairs(docks) do
\tif not env.dockGuis[d] then
\t\tfail("dock gui not created: " .. d)
\tend
end

local needles = {
${cfg.needles.map((n) => `\t${luaStr(n)},`).join("\n")}
}
for _, n in ipairs(needles) do
\tlocal found = false
\tfor _, p in ipairs(env.prints) do
\t\tif p:find(n, 1, true) then
\t\t\tfound = true
\t\t\tbreak
\t\tend
\tend
\tif not found then
\t\tfail("missing output line: " .. n .. " (prints: " .. table.concat(env.prints, " | ") .. ")")
\tend
end

print("SMOKE OK (${cfg.label})")
`;
}
